# Generated by Django 5.2 on 2025-04-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memories',
            options={'ordering': ['id'], 'verbose_name': 'Memorias'},
        ),
    ]
