# Generated by Django 5.2 on 2025-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_memories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
